# Copyright 2020-2024 Chris Croome
#
# This file is part of the Webarchitects RabbitMQ role.
#
# The Webarchitects RabbitMQ role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects RabbitMQ role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects RabbitMQ role. If not, see <https://www.gnu.org/licenses/>.
---
- name: RabbitMQ check tasks
  block:

    - name: Gather listening ports facts
      community.general.listen_ports_facts:

    - name: Set a fact for the RabbitMQ listening ports list
      ansible.builtin.set_fact:
        rabbitmq_ports: "{{ ansible_facts.tcp_listen | community.general.json_query(rabbitmq_jpq.ports) }}"

    - name: Debug RabbitMQ listening ports list
      ansible.builtin.debug:
        var: rabbitmq_ports
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Set a fact for the RabbitMQ systemd service
      ansible.builtin.set_fact:
        rabbitmq_systemd_service: "{{ ansible_facts.services | community.general.json_query(rabbitmq_jpq.service) }}"

    - name: Debug RabbitMQ systemd service
      ansible.builtin.debug:
        var: rabbitmq_systemd_service
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

    - name: Check that RabbitMQ is enabled and running
      ansible.builtin.assert:
        that:
          - rabbitmq_systemd_service.status == "enabled"
          - rabbitmq_systemd_service.state == "running"
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Check RabbitMQ cluster status
      ansible.builtin.command: rabbitmq-diagnostics cluster_status --formatter=json
      check_mode: false
      changed_when: false
      register: rabbitmq_cluster_status_check

    - name: Set a fact for rabbitmq-diagnostics cluster_status
      ansible.builtin.set_fact:
        rabbitmq_cluster_status: "{{ rabbitmq_cluster_status_check.stdout | from_json }}"

    - name: Debug rabbitmq_cluster_status
      ansible.builtin.debug:
        var: rabbitmq_cluster_status
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"

    - name: Debug rabbitmq_cluster_status.listeners
      ansible.builtin.debug:
        var: rabbitmq_cluster_status.listeners
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

    - name: Set a fact for the RabbitMQ node names
      ansible.builtin.set_fact:
        rabbitmq_node_names: "{{ rabbitmq_cluster_status.listeners | dict2items | community.general.json_query('[].key') }}"

    - name: Debug rabbitmq_node_names
      ansible.builtin.debug:
        var: rabbitmq_node_names
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

    - name: Check RabbitMQ environment
      ansible.builtin.command: rabbitmq-diagnostics environment --formatter=json
      check_mode: false
      changed_when: false
      register: rabbitmq_environment_check

    - name: Set a fact for rabbitmq-diagnostics environment
      ansible.builtin.set_fact:
        rabbitmq_environment: "{{ rabbitmq_environment_check.stdout | from_json }}"

    - name: Debug rabbitmq_environment
      ansible.builtin.debug:
        var: rabbitmq_environment
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}1{% else %}2{% endif %}"

    - name: Check RabbitMQ users
      ansible.builtin.command: rabbitmqctl list_users --formatter=json
      check_mode: false
      changed_when: false
      register: rabbitmq_list_users_check

    - name: Debug rabbitmq_list_users
      ansible.builtin.debug:
        var: rabbitmq_list_users_check
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

    - name: Set a fact for rabbitmqctl list_users
      ansible.builtin.set_fact:
        rabbitmq_list_users: "{{ rabbitmq_list_users_check.stdout | from_json }}"

    - name: Debug rabbitmq_list_users
      ansible.builtin.debug:
        var: rabbitmq_list_users
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

  tags:
    - rabbitmq
...
