---
- name: RabbitMQ user ppassword
  block:

    - name: Password in root file
      shell: "pwgen -n 20 1 > /root/.rabbitmq.{{ rabbitmq_user }}.passwd"
      creates: "/root/.rabbitmq.{{ rabbitmq_user }}.passwd"
      no_log: true

    - name: Password read from root file
      slurp:
        src: "/root/.rabbitmq.{{ rabbitmq_user }}.passwd"
      register: rabbitmq_password_b64encoded

    - name: Fact set for password string
      set_fact:
        rabbitmq_password: "{{ rabbitmq_password_b64encoded['content'] | b64decode | trim }}"

  tags:
    - rabbitmq
...
