---
- name: RabbitMQ user password present
  block:

    - name: Password in root file
      ansible.builtin.shell: "pwgen -n 20 1 > /root/.rabbitmq.{{ rabbitmq_user }}.passwd"
      args:
        creates: "/root/.rabbitmq.{{ rabbitmq_user }}.passwd"
      no_log: true

    - name: Password read from root file
      ansible.builtin.slurp:
        src: "/root/.rabbitmq.{{ rabbitmq_user }}.passwd"
      register: rabbitmq_password_b64encoded

    - name: Fact set for password string
      ansible.builtin.set_fact:
        rabbitmq_password: "{{ rabbitmq_password_b64encoded['content'] | b64decode | trim }}"

  tags:
    - rabbitmq
...
