---
- name: RabbitMQ user present
  block:

    - name: Include password tasks
      ansible.builtin.include_tasks: password.yml

    - name: RabbitMQ user present
      community.rabbitmq.rabbitmq_user:
        user: "{{ rabbitmq_user }}"
        password: "{{ rabbitmq_password }}"
        update_password: always
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present

  tags:
    - rabbitmq
...
