# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects RabbitMQ role.
#
# The Webarchitects RabbitMQ role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects RabbitMQ role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects RabbitMQ role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Run as root
  # become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Debug ansible_effective_user_id
      ansible.builtin.debug:
        var: ansible_effective_user_id

    - name: Debug ansible_user_id
      ansible.builtin.debug:
        var: ansible_user_id

    - name: Debug ansible_user_dir
      ansible.builtin.debug:
        var: ansible_user_dir

    - name: Gather facts
      ansible.builtin.setup:

    - name: Run hostname -f
      ansible.builtin.command: hostname -f
      check_mode: false
      changed_when: false
      register: molecule_hostname_f

    - name: Set a fact for the hostname
      ansible.builtin.set_fact:
        molecule_hostname: "{{ molecule_hostname_f.stdout }}"

    - name: Include /etc/hosts role as root
      ansible.builtin.include_role:
        name: etchosts
      vars:  # noqa var-naming[no-role-prefix]
        etchosts: true
        etchosts_file:
          - ip: 127.0.0.1
            hostname:
              - localhost
          - ip: "{{ ansible_default_ipv4.address }}"
            hostname:
              - "{{ molecule_hostname }}"
          - ip: ::1
            hostname:
              - ip6-localhost
              - ip6-loopback
          - ip: fe00::0
            hostname:
              - ip6-localnet
          - ip: ff00::0
            hostname:
              - ip6-mcastprefix
          - ip: ff02::1
            hostname:
              - ip6-allnodes
          - ip: ff02::2
            hostname:
              - ip6-allrouters
          - ip: ff02::3
            hostname:
              - ip6-allhosts
        etchosts_hostname_strategy: systemd
        etchosts_unsafe_writes: true

    - name: Include RabbitMQ role as root
      ansible.builtin.include_role:
        name: rabbitmq
      vars:  # noqa var-naming[no-role-prefix]
        rabbitmq: true
        rabbitmq_users:
          - username: ansible
            state: present
        rabbitmq_configuration:
          listeners.tcp.local: "{{ ansible_default_ipv4.address }}:5672"
        rabbitmq_systemd_units:
          - name: epmd.service
            files:
              - path: /etc/systemd/system/epmd.service.d/override.conf
                conf:
                  Service:
                    Environment: 'ERL_EPMD_ADDRESS="{{ ansible_default_ipv4.address }}"'
...
